### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Noorshavalli**
please review read me file @dnshavalli

### CODE REVIEW

**Review by Noorshavalli — COMMENTED** [review]
use capitalize in readme @nshavalli

**Review by dnshavalli — CHANGES_REQUESTED** [review]
Thanks add new feature doc for customer support

**Comment by Noorshavalli** [comment]
pls do review, changes are done

**Review by dnshavalli — APPROVED** [review]
review completed

**Comment by Noorshavalli** [comment]
Thanks

**Review by dnshavalli — COMMENTED** [review]
adding to master branch

**Comment by dnshavalli** [comment]
New changes merged into master branch

**Pull request merged**
